# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVC-snapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVC-snapKit
    pod 'Kingfisher', '~> 6.0'
    pod 'SnapKit', '~> 5.0.0'

end
