# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-MVVM-Combine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-MV
  pod 'Moya/Combine', '~> 15.0.0-alpha.1'

  pod 'Kingfisher', '~> 6.3.0'

  target 'SwiftUI-MVVM-CombineTests' do
     
  end
end
