# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'MVVM-RxSwift-coreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-RxSwift-coreData
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4.0'

    pod 'Kingfisher', '~> 6.0'
    pod 'SnapKit', '~> 5.0.0'
    pod 'Then', '~> 2.7.0'

    target 'MVVM-RxSwift-coreDataTests' do
      pod 'RxSwift', '~> 5'

      # Test
      pod 'RxTest', '~> 5'
      pod 'Nimble', '~> 9'
    end

end
