# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'ReactorKit-RxFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactorKit-RxFlow
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4.0'

    pod 'Moya/RxSwift', '~> 14.0'
    pod 'ReactorKit', '~> 2.1.1'
    pod 'RxFlow', '~> 2.11.0'

    pod 'Kingfisher', '~> 6.0'
    pod 'SnapKit', '~> 5.0.0'
    pod 'Then', '~> 2.7.0'

    target 'ReactorKit-RxFlowTests' do
      pod 'RxSwift', '~> 5'
   
      # Test
      pod 'RxExpect', '~> 2' 
    end

end
