# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'


target 'MVVM-RxSwift-tuist' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-RxSwift-tuist
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4.0'

    pod 'Kingfisher', '~> 6.0'

    target 'MVVM-RxSwift-tuistTests' do
      pod 'RxSwift', '~> 5'

      # Test
      pod 'RxTest', '~> 5'
    end

end
